version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "12345:12345"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - ALIAS=client1
    stdin_open: true
    tty: true

  sim:
    build:
      context: ./sim
      dockerfile: Dockerfile
    depends_on:
      - server
    stdin_open: true
    tty: true

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server